version: "3.9"
services:
  java_app:
    container_name: java_app
    image: crud-java:1.0
    build: .
    ports:
      - "8081:8080"
    environment:
      - conexion=jdbc:mariadb://java_db:3306/mariadb
    depends_on:
      - java_db
  java_db:
    container_name: java_db
    image: mariadb:latest
    ports:
      - "3304:3306"
    environment:
      MYSQL_USER: mariadb
      MYSQL_PASSWORD: mariadb
      MYSQL_DATABASE: mariadb
      